import {ReactNode,useState} from "react";
import {X,Check,Plus,Trash2,Edit3,Flame,PartyPopper,Send,Mail,MessageCircle} from "lucide-react";
import type {Task} from "./types";
import {today} from "./lib/date";

export function Btn({children,onClick,secondary=false}:any){return <button onClick={onClick} className={`inline-flex items-center justify-center gap-1.5 px-4 py-2.5 rounded-xl font-bold transition ${secondary?"bg-white/5 border border-white/10 hover:bg-white/10 hover:border-white/20":"bg-[#43f58f] text-[#03140b] shadow-[0_8px_24px_rgba(67,245,143,.14)] hover:bg-[#6bffa8] hover:shadow-[0_10px_30px_rgba(67,245,143,.24)]"}`}>{children}</button>}
export function Card({children,className=""}:{children:ReactNode,className?:string}){return <div className={`glass premium-card rounded-2xl p-5 ${className}`}>{children}</div>}
export function Modal({children,onClose}:{children:ReactNode;onClose:()=>void}){return <div className="fixed inset-0 z-50 bg-black/75 backdrop-blur-sm grid place-items-center p-4"><div className="w-full max-w-lg glass rounded-3xl p-6 relative animate-rise"><button onClick={onClose} aria-label="Close" className="absolute right-4 top-4 p-2 rounded-full bg-white/5 hover:bg-white/10"><X size={18}/></button>{children}</div></div>}
export function TaskModal({task,onClose,onSave}:{task?:Task|null;onClose:()=>void;onSave:(v:any)=>void}){
 const [title,setTitle]=useState(task?.title||"");const [description,setDescription]=useState(task?.description||"");const [category,setCategory]=useState(task?.category||"Personal");const [priority,setPriority]=useState(task?.priority||"Medium");const [due,setDue]=useState(task?.due_date||today());
 return <Modal onClose={onClose}><p className="text-xs uppercase tracking-[.2em] text-[#43f58f] font-bold">Your next win</p><h2 className="text-2xl font-black mb-5 mt-1">{task?"Edit task":"Add task"}</h2><div className="space-y-3">
 <input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="What needs to be done?" className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 outline-none focus:border-[#43f58f]"/>
 <textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description (optional)" className="w-full bg-white/5 border border-white/10 rounded-xl px-4 py-3 min-h-24 outline-none"/>
 <div className="grid grid-cols-1 sm:grid-cols-3 gap-2"><select value={category} onChange={e=>setCategory(e.target.value)} className="bg-[#0c2118] border border-white/10 rounded-xl px-3 py-3"><option>Personal</option><option>Work</option><option>Study</option><option>Health</option><option>Mind</option></select><select value={priority} onChange={e=>setPriority(e.target.value)} className="bg-[#0c2118] border border-white/10 rounded-xl px-3 py-3"><option>Low</option><option>Medium</option><option>High</option></select><input type="date" value={due} onChange={e=>setDue(e.target.value)} className="bg-[#0c2118] border border-white/10 rounded-xl px-3 py-3"/></div>
 <Btn onClick={()=>{if(title.trim())onSave({title:title.trim(),description:description||null,category,priority,due_date:due})}}><Plus size={16}/>{task?"Save changes":"Add task"}</Btn></div></Modal>
}
export function Celebration({quote,onClose}:{quote:any;onClose:()=>void}){return <Modal onClose={onClose}><div className="text-center py-5"><div className="text-6xl mb-4 animate-bounce">🎉</div><h2 className="text-3xl font-black text-[#43f58f]">Congratulations!</h2><p className="text-slate-300 mt-2">You've completed all your tasks for today.</p><Card className="mt-6 text-left"><p className="text-lg font-semibold">“{quote.quote}”</p><p className="text-sm text-slate-400 mt-2">— {quote.author}</p></Card><div className="mt-5"><Btn onClick={onClose}>Awesome! <Flame size={16} className="inline"/></Btn></div></div></Modal>}
